name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x"
          channel: "stable"
          cache: true

      - name: Configure Project Name and Dependencies
        run: |
          # Actualizar el nombre del paquete en el pubspec.yaml actual usando guion bajo
          sed -i "s/^name:.*/name: partfinder_mobile/" pubspec.yaml
          
          # Renombrar el directorio actual para cumplir con Dart (de guion medio a guion bajo)
          cd ..
          mv partfinder-mobile partfinder_mobile
          cd partfinder_mobile

          # Obtener dependencias y compilar directamente aquí
          flutter pub get
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
